sonar.projectKey=crgolden_Products
sonar.organization=crgolden

sonar.sources=Products
sonar.tests=Products.Tests
sonar.exclusions=**/bin/**,**/obj/**

sonar.cs.vscoveragexml.reportsPaths=coverage.xml
